### ISSUE TITLE
Fix the prevMR error

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#381]
panic: Error found in validating directory blocks: Previous merkle root not matching for Dir block: 

goroutine 15 [running]:
runtime.panic(0x906840, 0xc2102ec8a0)
	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/FactomProject/btcd.init_processor()
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go:221 +0x870
github.com/FactomProject/btcd.Start_Processor(0x7f8ba55fd8c0, 0xc2102ea8a0, 0xc2102c8800, 0xc2102e5000, 0xc2102e5800, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factomprocessor.go:239 +0x9b
created by main.factomdMain
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:89 +0x7f

**Comment by JackXLu** [comment]
//??return errors.New("Previous merkle root not matching for Dir block: " + string(i))
