### ISSUE TITLE
Nil pointer exception for MemPool.addBlockMsg

### ISSUE THREAD

**Issue by JackXLu** [FactomProject/WorkItems#471]
## TRACE: 2015-07-07.15:58:00 line 66 github.com/FactomProject/FactomCode/process.processABlock file: /home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/syncup.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x40809f]

goroutine 17 [running]:
runtime.panic(0xaf5be0, 0x16f5328)
	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/FactomProject/FactomCode/process.(*ftmMemPool).addBlockMsg(0xc2101010f0, 0x7f114c0754c8, 0xc2137f5f88, 0xc21200cd70, 0x40, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/mempool.go:66 +0xb8
github.com/FactomProject/FactomCode/process.processABlock(0xc2137f5f88, 0x7f114c075508, 0xc2137f5f88)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/syncup.go:75 +0x1b9
github.com/FactomProject/FactomCode/process.serveMsgRequest(0x7f114c075508, 0xc2137f5f88, 0x1e, 0x7f114e834ef0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:374 +0x483
github.com/FactomProject/FactomCode/process.Start_Processor(0x7f114e9d5c28, 0xc210101b40, 0xc21011c000, 0xc21011c800, 0xc21011d000, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/process/processor.go:193 +0x238
created by main.factomdMain
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:88 +0x7a

goroutine 1 [chan receive]:
github.com/FactomProject/btcd.btcdMain(0x0, 0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/btcd.go:156 +0x69f
github.com/FactomProject/btcd.Start_btcd(0x7f114e9d5c28, 0xc210101b40, 0xc21011c000, 0xc21011c800, 0xc21011d000, ...)
	/home/jlu/workspace2/go/src/github.com/FactomProject/btcd/factom.go:186 +0x1b6
main.factomdMain(0x0, 0x0)
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:108 +0x291
main.main()
	/home/jlu/workspace2/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:79 +0x238

**Comment by JackXLu** [comment]
Not re-producible. probably due to initialization
