### ISSUE TITLE
Error stopping and restarting a Client factomd while running against our servers

### ISSUE THREAD

**Issue by PaulSnow** [FactomProject/WorkItems#559]
Stopping and starting the client some time later yielded this error:
```
13:40:23 2015-07-23 [INF] BMGR: Syncing to block height 1249 from peer 54.218.32.159:8108
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45188f]

goroutine 22 [running]:
github.com/FactomProject/FactomCode/common.(*Entry).MarshalBinary(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/paul/factom/go/src/github.com/FactomProject/FactomCode/common/entry.go:63 +0x57f
github.com/FactomProject/FactomCode/common.(*EChain).MarshalBinary(0xc209186ea0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/paul/factom/go/src/github.com/FactomProject/FactomCode/common/echain.go:33 +0xd7
github.com/FactomProject/FactomCode/database/ldb.(*LevelDb).InsertChain(0xc20804f6d0, 0xc209186ea0, 0x0, 0x0)
	/home/paul/factom/go/src/github.com/FactomProject/FactomCode/database/ldb/eblock.go:155 +0x128
github.com/FactomProject/FactomCode/process.storeBlocksFromMemPool(0xc209abc960, 0xc208222000, 0x7fee6aaed640, 0xc20804f6d0, 0x0, 0x0)
	/home/paul/factom/go/src/github.com/FactomProject/FactomCode/process/syncup.go:300 +0xc7f
github.com/FactomProject/FactomCode/process.validateAndStoreBlocks(0xc208222000, 0x7fee6aaed640, 0xc20804f6d0, 0xc208220040, 0xc20811a180)
	/home/paul/factom/go/src/github.com/FactomProject/FactomCode/process/syncup.go:160 +0x14f
created by github.com/FactomProject/FactomCode/process.Start_Processor
	/home/paul/factom/go/src/github.com/FactomProject/FactomCode/process/processor.go:190 +0x4f2

<followed my more stack traces>
```

**Comment by PaulSnow** [comment]
Not reproducible.
