### ISSUE TITLE
panic in factoid test on older machine

### ISSUE THREAD

**Issue by m21** [FactomProject/WorkItems#567]
Need better checks in those tests.
Additional debugging statements, info.
```
go/src/github.com/FactomProject/factoid> go test -v
=== RUN Test_AddressEquals
--- PASS: Test_AddressEquals (0.00 seconds)
=== RUN Test_Factoid_Addresses
addr  d9431b76032aca43af2a90c7d6e110e57ffe94cf71ef1cb25b1dcb7900770ef1
FA3cmE7pGzNhoGi5ro1bXMFpLn78mBpbjMQumx989kS9fLMxvnGj
--- FAIL: Test_Factoid_Addresses (0.00 seconds)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 4 [running]:
runtime.panic(0x55b6a0, 0x742daa)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
testing.func·005()
	/usr/lib/go/src/pkg/testing/testing.go:385 +0xe8
runtime.panic(0x55b6a0, 0x742daa)
	/usr/lib/go/src/pkg/runtime/panic.c:248 +0x106
github.com/FactomProject/factoid.validateUserStr(0x72600a, 0x2, 0x2, 0xc21004f8c0, 0x34, ...)
	//go/src/github.com/FactomProject/factoid/util.go:242 +0x25b
github.com/FactomProject/factoid.ValidateFUserStr(0xc21004f8c0, 0x34, 0x34)
	//go/src/github.com/FactomProject/factoid/util.go:255 +0x58
github.com/FactomProject/factoid.Test_Factoid_Addresses(0xc210055120)
	//go/src/github.com/FactomProject/factoid/address_test.go:78 +0x584
testing.tRunner(0xc210055120, 0x742098)
	/usr/lib/go/src/pkg/testing/testing.go:391 +0x8b
created by testing.RunTests
	/usr/lib/go/src/pkg/testing/testing.go:471 +0x8b2

goroutine 1 [chan receive]:
testing.RunTests(0x5d4a38, 0x742080, 0xf, 0xf, 0x1)
	/usr/lib/go/src/pkg/testing/testing.go:472 +0x8d5
testing.Main(0x5d4a38, 0x742080, 0xf, 0xf, 0x745d00, ...)
	/usr/lib/go/src/pkg/testing/testing.go:403 +0x84
main.main()
	github.com/FactomProject/factoid/_test/_testmain.go:75 +0x9c
exit status 2
FAIL	github.com/FactomProject/factoid	0.003s
```

**Comment by PaulSnow** [comment]
Not reproducible.

**Comment by m21** [comment]
Will retest on a freshly created AWS instance.

**Comment by m21** [comment]
Same panic on another AWS server.
It was decided that 1.2 must not be used this item will take care of it: https://github.com/FactomProject/WorkItems/issues/591
