### ISSUE TITLE
factomd won't start after having synced to some particular db (ubuntu)

### ISSUE THREAD

**Issue by pdobacz** [FactomProject/WorkItems#961]
I get the following crash, when trying to run the daemon

```
user@user:~$ factomd
2016/02/08 12:20:24 read factom config file:  /home/user/.factom/factomd.conf
2016/02/08 12:20:24 ERROR Reading config file!
Server starting with default settings...
 open /home/user/.factom/factomd.conf: no such file or directory
Go compiler version:  go1.5.1
boltDBpath: /home/user/.factom/
2016/02/08 12:20:24 web.go serving :8088

'factomd initializeonly' will do just that.  Initialize and stop.


>>>>>>>>>>>>>>>>>  CLIENT MODE <<<<<<<<<<<<<<<<<<<<<<<


12:20:26 2016-02-08 [WRN] BTCD: open /home/user/.factom/NONE.conf: no such file or directory
peers.json is disabled for Milestone1
12:20:26 2016-02-08 [INF] BTCD: Version 0.9.0-beta
12:20:26 2016-02-08 [INF] SRVR: Server listening on 0.0.0.0:8108 ; MaxPeers= 125
12:20:26 2016-02-08 [INF] SRVR: Server listening on [::]:8108 ; MaxPeers= 125
12:20:26 2016-02-08 [INF] RPCS: RPC server listening on 127.0.0.1:8384
12:20:26 2016-02-08 [INF] DISC: 1 addresses found from DNS seed factom.network
panic: Error in initializing dChain:000000000000000000000000000000000000000000000000000000000000000c DBHeight:22880 i:22881

goroutine 54 [running]:
github.com/FactomProject/FactomCode/process.initECChain()
    /home/brian/go/src/github.com/FactomProject/FactomCode/process/init.go:93 +0x305
github.com/FactomProject/FactomCode/process.initProcessor()
    /home/brian/go/src/github.com/FactomProject/FactomCode/process/processor.go:127 +0x387
github.com/FactomProject/FactomCode/process.Start_Processor(0xf75002a0, 0x193413b0, 0x19344f80, 0x19344fc0, 0x19345000, 0x19345040)
    /home/brian/go/src/github.com/FactomProject/FactomCode/process/processor.go:188 +0xbf
created by main.factomdMain
    /home/brian/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:100 +0x8e

goroutine 1 [chan receive]:
github.com/FactomProject/btcd.btcdMain(0x0, 0x0, 0x0)
    /home/brian/go/src/github.com/FactomProject/btcd/btcd.go:152 +0x57f
github.com/FactomProject/btcd.Start_btcd(0xf75002a0, 0x193413b0, 0x19344f80, 0x19344fc0, 0x19345000, 0x19345040, 0x19317390, 0x8, 0x19317740, 0xb, ...)
    /home/brian/go/src/github.com/FactomProject/btcd/factom.go:197 +0x1f5
main.factomdMain(0x0, 0x0)
    /home/brian/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:130 +0x3a7
main.main()
    /home/brian/go/src/github.com/FactomProject/FactomCode/factomd/factomd.go:91 +0x852

goroutine 5 [semacquire]:
sync.runtime_Syncsemacquire(0x19005ca8)
    /usr/local/go/src/runtime/sema.go:237 +0x1ef
sync.(*Cond).Wait(0x19005ca0)
    /usr/local/go/src/sync/cond.go:62 +0x85
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processItem(0x18f15e00, 0x0)
    /home/brian/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:50 +0xaf
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processQueue(0x18f15e00)
    /home/brian/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:63 +0x2a
created by github.com/btcsuitereleases/seelog.newAsyncLoopLogger
    /home/brian/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:40 +0x79

goroutine 6 [semacquire]:
sync.runtime_Syncsemacquire(0x19005e48)
    /usr/local/go/src/runtime/sema.go:237 +0x1ef
sync.(*Cond).Wait(0x19005e40)
    /usr/local/go/src/sync/cond.go:62 +0x85
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processItem(0x18f15e80, 0x0)
    /home/brian/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:50 +0xaf
github.com/btcsuitereleases/seelog.(*asyncLoopLogger).processQueue(0x18f15e80)
    /home/brian/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:63 +0x2a
created by github.com/btcsuitereleases/seelog.newAsyncLoopLogger
    /home/brian/go/src/github.com/btcsuitereleases/seelog/behavior_asynclooplogger.go:40 +0x79

goroutine 17 [semacquire]:
sync.runtime_Syncsemacquire(0x1933d708)
    /usr/local/go/src/runtime/sema.go:237 +0x1ef
sync.(*Cond).Wait(0x1933d700)
    /usr/local/go/src/sync/cond.go:62 +0x85
github.com/FactomProject/seelog.(*asyncLoopLogger).processItem(0x19344a40, 0x0)
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:50 +0xaf
github.com/FactomProject/seelog.(*asyncLoopLogger).processQueue(0x19344a40)
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:63 +0x2a
created by github.com/FactomProject/seelog.newAsyncLoopLogger
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:40 +0x79

goroutine 18 [semacquire]:
sync.runtime_Syncsemacquire(0x1933d888)
    /usr/local/go/src/runtime/sema.go:237 +0x1ef
sync.(*Cond).Wait(0x1933d880)
    /usr/local/go/src/sync/cond.go:62 +0x85
github.com/FactomProject/seelog.(*asyncLoopLogger).processItem(0x19344ac0, 0x0)
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:50 +0xaf
github.com/FactomProject/seelog.(*asyncLoopLogger).processQueue(0x19344ac0)
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:63 +0x2a
created by github.com/FactomProject/seelog.newAsyncLoopLogger
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_asynclooplogger.go:40 +0x79

goroutine 19 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x36

goroutine 20 [IO wait]:
net.runtime_pollWait(0xf75cda20, 0x72, 0x193192b0)
    /usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x19313278, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x19313278, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x19313240, 0x0, 0xf75cdab8, 0x193192c0)
    /usr/local/go/src/net/fd_unix.go:408 +0x20b
net.(*TCPListener).AcceptTCP(0x1932e030, 0x8093d30, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net/http.tcpKeepAliveListener.Accept(0x1932e030, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2135 +0x3d
net/http.(*Server).Serve(0x19313200, 0xf75cda98, 0x1932e030, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0x98
net/http.(*Server).ListenAndServe(0x19313200, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1877 +0xe4
net/http.ListenAndServe(0x193192a0, 0x5, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1967 +0x7a
github.com/FactomProject/FactomCode/controlpanel.runPanel()
    /home/brian/go/src/github.com/FactomProject/FactomCode/controlpanel/webserver.go:162 +0x157
created by github.com/FactomProject/FactomCode/controlpanel.(*ControlPanel).Run
    /home/brian/go/src/github.com/FactomProject/FactomCode/controlpanel/controlpanel.go:100 +0x83

goroutine 21 [select]:
github.com/FactomProject/goleveldb/leveldb/util.(*BufferPool).drain(0x1936a4d0)
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/util/buffer_pool.go:205 +0x207
created by github.com/FactomProject/goleveldb/leveldb/util.NewBufferPool
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/util/buffer_pool.go:236 +0x1da

goroutine 49 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).compactionError(0x1940c0d0)
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db_compaction.go:120 +0x3fd
created by github.com/FactomProject/goleveldb/leveldb.openDB
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:126 +0x70d

goroutine 50 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).mpoolDrain(0x1940c0d0)
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db_state.go:73 +0x11a
created by github.com/FactomProject/goleveldb/leveldb.openDB
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:127 +0x72a

goroutine 51 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).tCompaction(0x1940c0d0)
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db_compaction.go:812 +0x5fe
created by github.com/FactomProject/goleveldb/leveldb.openDB
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:130 +0x76c

goroutine 52 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).mCompaction(0x1940c0d0)
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db_compaction.go:759 +0x202
created by github.com/FactomProject/goleveldb/leveldb.openDB
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:131 +0x789

goroutine 53 [select]:
github.com/FactomProject/goleveldb/leveldb.(*DB).jWriter(0x1940c0d0)
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db_write.go:37 +0x158
created by github.com/FactomProject/goleveldb/leveldb.openDB
    /home/brian/go/src/github.com/FactomProject/goleveldb/leveldb/db.go:132 +0x7a6

goroutine 55 [IO wait]:
net.runtime_pollWait(0xf75cd9a8, 0x72, 0x193428e0)
    /usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x18f15df8, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x18f15df8, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x18f15dc0, 0x0, 0xf75cdab8, 0x193428f0)
    /usr/local/go/src/net/fd_unix.go:408 +0x20b
net.(*TCPListener).AcceptTCP(0x18f0b2c8, 0x8093d30, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net.(*TCPListener).Accept(0x18f0b2c8, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x39
net/http.(*Server).Serve(0x18f15f80, 0xf75cca60, 0x18f0b2c8, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0x98
net/http.Serve(0xf75cca60, 0x18f0b2c8, 0xf75003f8, 0x19333240, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1765 +0x74
github.com/hoisie/web.(*Server).Run(0x193700a0, 0x19342730, 0x5)
    /home/brian/go/src/github.com/hoisie/web/server.go:155 +0x670
created by github.com/FactomProject/FactomCode/wsapi.Start
    /home/brian/go/src/github.com/FactomProject/FactomCode/wsapi/wsapi.go:69 +0x637

goroutine 25 [select, locked to thread]:
runtime.gopark(0x8920e90, 0x19820f8c, 0x87c36b8, 0x6, 0x8ce3f18, 0x2)
    /usr/local/go/src/runtime/proc.go:185 +0x12d
runtime.selectgoImpl(0x19820f8c, 0x0, 0xc)
    /usr/local/go/src/runtime/select.go:392 +0x9ee
runtime.selectgo(0x19820f8c)
    /usr/local/go/src/runtime/select.go:212 +0xf
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal1_unix.go:227 +0x2f9
runtime.goexit()
    /usr/local/go/src/runtime/asm_386.s:1662 +0x1

goroutine 24 [semacquire]:
sync.runtime_Syncsemacquire(0x1e18b828)
    /usr/local/go/src/runtime/sema.go:237 +0x1ef
sync.(*Cond).Wait(0x1e18b820)
    /usr/local/go/src/sync/cond.go:62 +0x85
github.com/FactomProject/seelog.(*asyncAdaptiveLogger).processItem(0x19356be0, 0x1bbb0800, 0x0)
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_adaptivelogger.go:94 +0xc3
github.com/FactomProject/seelog.(*asyncAdaptiveLogger).processQueue(0x19356be0)
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_adaptivelogger.go:119 +0x2a
created by github.com/FactomProject/seelog.newAsyncAdaptiveLogger
    /home/brian/go/src/github.com/FactomProject/seelog/behavior_adaptivelogger.go:84 +0x3f5

goroutine 26 [select]:
github.com/FactomProject/btcd.mainInterruptHandler()
    /home/brian/go/src/github.com/FactomProject/btcd/signal.go:35 +0x23b
created by github.com/FactomProject/btcd.addInterruptHandler
    /home/brian/go/src/github.com/FactomProject/btcd/signal.go:80 +0xd8

goroutine 37 [IO wait]:
net.runtime_pollWait(0xf75cd930, 0x72, 0x1e8b6960)
    /usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x1e2d0438, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x1e2d0438, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x1e2d0400, 0x0, 0xf75cdab8, 0x1e8b6970)
    /usr/local/go/src/net/fd_unix.go:408 +0x20b
net.(*TCPListener).AcceptTCP(0x1e1a8b08, 0x886cbc0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net.(*TCPListener).Accept(0x1e1a8b08, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x39
github.com/FactomProject/btcd.(*server).listenHandler(0x18f6a900, 0xf75cca60, 0x1e1a8b08)
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:509 +0x16b
created by github.com/FactomProject/btcd.(*server).Start
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:924 +0x19b

goroutine 38 [IO wait]:
net.runtime_pollWait(0xf75cd8b8, 0x72, 0x1e8b69a0)
    /usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x1e2d0478, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x1e2d0478, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x1e2d0440, 0x0, 0xf75cdab8, 0x1e8b69b0)
    /usr/local/go/src/net/fd_unix.go:408 +0x20b
net.(*TCPListener).AcceptTCP(0x1e1a8b18, 0x886cbc0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net.(*TCPListener).Accept(0x1e1a8b18, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x39
github.com/FactomProject/btcd.(*server).listenHandler(0x18f6a900, 0xf75cca60, 0x1e1a8b18)
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:509 +0x16b
created by github.com/FactomProject/btcd.(*server).Start
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:924 +0x19b

goroutine 39 [select]:
github.com/FactomProject/btcd.(*server).peerHandler(0x18f6a900)
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:617 +0x115f
created by github.com/FactomProject/btcd.(*server).Start
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:930 +0x1f2

goroutine 40 [select]:
github.com/FactomProject/btcd.(*server).rebroadcastHandler(0x18f6a900)
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:863 +0x4f7
created by github.com/FactomProject/btcd.(*server).Start
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:942 +0x283

goroutine 41 [IO wait]:
net.runtime_pollWait(0xf75cd840, 0x72, 0x1e8b6a70)
    /usr/local/go/src/runtime/netpoll.go:157 +0x55
net.(*pollDesc).Wait(0x1e8b32f8, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).WaitRead(0x1e8b32f8, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).accept(0x1e8b32c0, 0x0, 0xf75cdab8, 0x1e8b6a80)
    /usr/local/go/src/net/fd_unix.go:408 +0x20b
net.(*TCPListener).AcceptTCP(0x1e1bf3d8, 0x8093e10, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x47
net.(*TCPListener).Accept(0x1e1bf3d8, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:264 +0x39
crypto/tls.(*listener).Accept(0x1e8b6910, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/tls.go:46 +0x53
net/http.(*Server).Serve(0x1e8b3300, 0xf74888b8, 0x1e8b6910, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:1887 +0x98
github.com/FactomProject/btcd.(*rpcServer).Start.func3(0x1e8b3300, 0x1e1da770, 0xf74888b8, 0x1e8b6910)
    /home/brian/go/src/github.com/FactomProject/btcd/rpcserver.go:350 +0xf9
created by github.com/FactomProject/btcd.(*rpcServer).Start
    /home/brian/go/src/github.com/FactomProject/btcd/rpcserver.go:353 +0x33b

goroutine 42 [select]:
github.com/FactomProject/btcd.queueHandler(0x1e2d0800, 0x1e2d0840, 0x1e2d08c0)
    /home/brian/go/src/github.com/FactomProject/btcd/rpcwebsocket.go:138 +0x31d
github.com/FactomProject/btcd.(*wsNotificationManager).queueHandler(0x1e1970e0)
    /home/brian/go/src/github.com/FactomProject/btcd/rpcwebsocket.go:179 +0x32
created by github.com/FactomProject/btcd.(*wsNotificationManager).Start
    /home/brian/go/src/github.com/FactomProject/btcd/rpcwebsocket.go:827 +0x50

goroutine 43 [select]:
github.com/FactomProject/btcd.(*wsNotificationManager).notificationHandler(0x1e1970e0)
    /home/brian/go/src/github.com/FactomProject/btcd/rpcwebsocket.go:291 +0xd5d
created by github.com/FactomProject/btcd.(*wsNotificationManager).Start
    /home/brian/go/src/github.com/FactomProject/btcd/rpcwebsocket.go:828 +0x6d

goroutine 44 [chan receive]:
github.com/FactomProject/btcd.factomForkInit.func1(0x18f6a900)
    /home/brian/go/src/github.com/FactomProject/btcd/factom.go:44 +0x50
created by github.com/FactomProject/btcd.factomForkInit
    /home/brian/go/src/github.com/FactomProject/btcd/factom.go:73 +0x56

goroutine 45 [chan receive]:
github.com/FactomProject/btcd.factomForkInit.func2()
    /home/brian/go/src/github.com/FactomProject/btcd/factom.go:76 +0x51
created by github.com/FactomProject/btcd.factomForkInit
    /home/brian/go/src/github.com/FactomProject/btcd/factom.go:131 +0x6b

goroutine 46 [semacquire]:
sync.runtime_Semacquire(0x18f6a974)
    /usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0x18f6a968)
    /usr/local/go/src/sync/waitgroup.go:126 +0xa4
github.com/FactomProject/btcd.(*server).WaitForShutdown(0x18f6a900)
    /home/brian/go/src/github.com/FactomProject/btcd/server.go:996 +0x2b
github.com/FactomProject/btcd.btcdMain.func4(0x18f6a900)
    /home/brian/go/src/github.com/FactomProject/btcd/btcd.go:145 +0x21
created by github.com/FactomProject/btcd.btcdMain
    /home/brian/go/src/github.com/FactomProject/btcd/btcd.go:148 +0x561

goroutine 47 [select]:
github.com/FactomProject/btcd/addrmgr.(*AddrManager).addressHandler(0x18f18580)
    /home/brian/go/src/github.com/FactomProject/btcd/addrmgr/addrmanager.go:347 +0x21f
created by github.com/FactomProject/btcd/addrmgr.(*AddrManager).Start
    /home/brian/go/src/github.com/FactomProject/btcd/addrmgr/addrmanager.go:558 +0x1cb

goroutine 48 [select]:
github.com/FactomProject/btcd.(*blockManager).blockHandler(0x1e1baae0)
    /home/brian/go/src/github.com/FactomProject/btcd/blockmanager.go:1064 +0x9af
created by github.com/FactomProject/btcd.(*blockManager).Start
    /home/brian/go/src/github.com/FactomProject/btcd/blockmanager.go:1347 +0x12b
```

When I remove my `~/.factom` it runs fine, until it syncs, after which I am unable to restart anymore.

Version:

```
user@user:~$ factomd -V
(...)
factomd version 0.9.0-beta
```

I am using the binaries retrieved from the "howto" page. I am not experiencing this on Windows.

**Comment by pdobacz** [comment]
update: since today I am getting the same issue on Windows

**Comment by pdobacz** [comment]
update: I just noticed on explorer, that this DB 22880 mentioned in the error message seems to have been the last which got anchored to BTC
http://explorer.factom.org/dblock/7bd9704ec9e8e5238fe7669cc235b56c109052e7a8be4281b2a985922c24e038

in case there is a connection there

**Comment by michaelbeam** [comment]
We are aware of the issue and we are releasing a new version of the code today that will fix the problem. You can fix the problem right away on your end if you git pull the latest master branch on all our repos, and clear your database (.factom/ldb .factom/data) otherwise you can get the installer for the new version (0.3.5) when we publish it today

**Comment by carryforward** [comment]
Thank you for pointing this out.  

if you pull and compile from source today, it will pull the fix.

to work around in the short term, delete the files in the .factom/ldb folder.  this will cause the blockchain to be downloaded again and will get you to current state.  the crash only happens when you restart.  if you want to restart, close factomd when there are less 20,000 blocks in .factom/data/000...0d, then copy the .factom directory.  when you restart it will start from <20,000, which is ok.

we are releasing binaries today which will fix the issue, so workaround will not be needed.

**Comment by pdobacz** [comment]
Yep, confirmed, v0.3.5 works fine on Ubuntu&Windows. Thank you!
